name: Onboard Grades Tracker

on:
  workflow_dispatch: # Permet de lancer manuellement l'action

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download grades.csv artifact
      uses: actions/download-artifact@v4
      with:
        name: grades
        path: .

    - name: Verify grades.csv exists
      run: |
        if [ -f "grades.csv" ]; then
          echo "grades.csv found!"
        else
          echo "grades.csv not found, creating an empty file."
          echo "Annee academique,UE,Cours,Epreuve,Coefficient,Note" > grades.csv
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9" # Version de Python à utiliser

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run the script
      env:
        LOGIN: ${{ secrets.LOGIN }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        source venv/bin/activate
        python main.py

    - name: Upload grades.csv as artifact
      uses: actions/upload-artifact@v4
      with:
        name: grades
        path: grades.csv