name: Onboard Grades Tracker

on:
  workflow_dispatch: # Permet de lancer manuellement l'action

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check if grades.csv artifact exists
      id: check-artifact
      run: |
        echo "Checking if grades.csv artifact exists..."
        curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "${{ github.api_url }}/repos/${{ github.repository }}/actions/artifacts" | \
          jq '[.artifacts[] | select(.name=="grades")] | sort_by(.created_at) | last' > artifact.json
        if [ -s artifact.json ]; then
          echo "artifact-exists=true" >> $GITHUB_ENV
          export ARTIFACT_URL=$(jq -r '.archive_download_url' artifact.json)
          echo "artifact-url=$ARTIFACT_URL" >> $GITHUB_ENV
        else
          echo "artifact-exists=false" >> $GITHUB_ENV
        fi

    - name: Debug artifact.json
      run: |
        echo "Contents of artifact.json:"
        cat artifact.json

    - name: Download grades.csv artifact
      if: env.artifact-exists == 'true'
      run: |
        echo "Downloading artifact from $ARTIFACT_URL"
        curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o grades.zip "$ARTIFACT_URL"
        unzip grades.zip
        rm grades.zip

    - name: Verify grades.csv exists
      run: |
        if [ -f "grades.csv" ]; then
          echo "grades.csv found!"
        else
          echo "grades.csv not found, creating an empty file."
          echo "Annee academique,UE,Cours,Epreuve,Coefficient,Note" > grades.csv
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9" # Version de Python à utiliser

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run the script
      env:
        LOGIN: ${{ secrets.LOGIN }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        source venv/bin/activate
        python main.py

    - name: Upload grades.csv as artifact
      uses: actions/upload-artifact@v4
      with:
        name: grades
        path: grades.csv